repository:
  jepersson/jepersson.github.io

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: :compressed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
