repository:
  jepersson/jepersson.github.io

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: :compressed

defaults:
  values:
    layout: "post"
    author: "Eric Persson"
    published: "False"

markdown: kramdown
highlighter: rouge
